= mini-getopt

Very simple wrapper for `getopt()` function.

:toc:

image:https://poser.pugx.org/jawira/mini-getopt/v/stable[Latest Stable Version,link=https://packagist.org/packages/jawira/mini-getopt]
image:https://poser.pugx.org/jawira/mini-getopt/downloads[Total Downloads,link=https://packagist.org/packages/jawira/mini-getopt]
image:https://poser.pugx.org/jawira/mini-getopt/license[License,link=https://packagist.org/packages/jawira/mini-getopt]
image:https://poser.pugx.org/jawira/mini-getopt/composerlock[composer.lock,link=https://packagist.org/packages/jawira/mini-getopt]
image:https://img.shields.io/badge/pds-skeleton-blue.svg?style=flat-square[PDS Skeleton,link=https://github.com/php-pds/skeleton]

== Usage

This library is composed of only one class : `\Jawira\MiniGetopt\MiniGetopt`.

Since this library is only a wrapper, you should know how `getopt()` function
works. Please read the documentation: http://php.net/manual/en/function.getopt.php[http://php.net/manual/en/function.getopt.php] 

To setup `MiniGetopt` class you should use one of the following methods:

* `MiniGetopt::addNoValue`
* `MiniGetopt::addOptional`
* `MiniGetopt::addRequired`

To retrieve the values at execution time use:

* `MiniGetopt::getOption`

=== Example

Imagine you have the following script:

.resources/demo.php
[source,php]
----
include::resources/demo.php[lines=7..100]
----
<1> When used a _required option_ expects to have a value.
<2> An _optional option_ may or may not have a value.
<3> A _no value option_ doesn't needs to have a value.
<4> _Default value_ (`png`) is used when an option is not used in command line.
<5> If _default value_ is not set, then `null` will be used.

=== Executing the example

// todo: execute demo.php

== How to install

Install using composer:

[source]
----
composer require jawira/mini-getopt
----

== Requirements

You will need `mbstring` extension.

== License

This library is licensed under the link:LICENSE.md[MIT].