name: QA

on: [ pull_request ]

jobs:

  phing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.4,8.0,8.1 ]
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: Phing Build
        uses: phingofficial/phing-github-action@main
        with:
          longtargets: true
          version: 3.0.0-rc3
          targets: behat:run phpstan:analyze psalm:run
