name: QA

on: [ pull_request ]

jobs:

  phing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.4,8.0,8.1,8.2,8.3 ]
    steps:
      - uses: actions/checkout@v4
      - uses: "ramsey/composer-install@v3"
      - name: Phing Build
        uses: phingofficial/phing-github-action@main
        with:
          longtargets: true
          version: 3.0.0
          targets: behat:run phpstan:analyze psalm:run
